services:
  user-interface:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: att-user-interface
    networks:
      - att-network
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json

networks:
  att-network: 