services:
  user-interface:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: att-user-interface
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json

networks:
  att-orchestrator_att-network:
    external: true
